"""add language

Revision ID: 72f97077f53c
Revises: 85dc37ec09f9
Create Date: 2016-03-14 18:56:27.403081

"""

# revision identifiers, used by Alembic.
revision = '72f97077f53c'
down_revision = '85dc37ec09f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('is_executable', sa.Boolean(), nullable=True))
    op.add_column('nodes', sa.Column('language', sa.String(length=8), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'language')
    op.drop_column('file', 'is_executable')
    ### end Alembic commands ###
