"""empty message

Revision ID: 85dc37ec09f9
Revises: 9c416c0640d3
Create Date: 2016-03-10 22:39:12.172159

"""

# revision identifiers, used by Alembic.
revision = '85dc37ec09f9'
down_revision = '9c416c0640d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('catkin_initialized', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'catkin_initialized')
    ### end Alembic commands ###
